### ISSUE TITLE
moving unitframes

### ISSUE THREAD

**Issue by k1ck3r** [kaytotes/ImprovedBlizzardUI#111]
trying to move unitframes i'm getting the following error
can you say what could be wrong? disabled all addons, beside IMP and WeakAuras, and i'm sure that couldn't be from any of my WA's

```
Message: Interface\FrameXML\PlayerFrame.lua:733: Frame PlayerFrame is not movable
Time: Tue Sep 11 19:35:41 2018
Count: 2
Stack: Interface\FrameXML\PlayerFrame.lua:733: Frame PlayerFrame is not movable
[C]: in function `StartMoving'
Interface\FrameXML\PlayerFrame.lua:733: in function <Interface\FrameXML\PlayerFrame.lua:732>

Locals: (*temporary) = PlayerFrame {
 0 = <userdata>
 portrait = PlayerPortrait {
 }
 healAbsorbBar = PlayerFrameHealAbsorbBar {
 }
 myManaCostPredictionBar = PlayerFrameManaCostPredictionBar {
 }
 PlayerFrameHealthBarAnimatedLoss = <unnamed> {
 }
 statusSign = -1
 unit = "player"
 healAbsorbBarRightShadow = PlayerFrameHealAbsorbBarRightShadow {
 }
 healAbsorbBarLeftShadow = PlayerFrameHealAbsorbBarLeftShadow {
 }
 menu = <function> defined @Interface\FrameXML\PlayerFrame.lua:53
 feedbackText = PlayerHitIndicator {
 }
 totalAbsorbBar = PlayerFrameTotalAbsorbBar {
 }
 totalAbsorbBarOverlay = PlayerFrameTotalAbsorbBarOverlay {
 }
 overHealAbsorbGlow = PlayerFrameOverHealAbsorbGlow {
 }
 statusCounter = 0
 healthbar = PlayerFrameHealthBar {
 }
 overAbsorbGlow = PlayerFrameOverAbsorbGlow {
 }
 manabar = PlayerFrameManaBar {
 }
 inSequence = false
 isAnimatedOut = false
 threatIndicator = PlayerFrameFlash {
 }
 state = "player"
 myHealPredictionBar = PlayerFrameMyHealPredictionBar {
 }
 name = PlayerName {
 }
 feedbackFontHeight = 30
 OnEvent = <function> defined @Interface\FrameXML\PlayerFrame.lua:157
 otherHealPredictionBar = PlayerFrameOtherHealPredictionBar {
 }
}
```

**Comment by mikevb1** [comment]
I remember having this issue with another addon. When an addon locks a frame, even if the player unlocks it, they won't be able to move it. I've been able to "fix" it by commenting out [modules/frames/player.lua#96](https://github.com/kaytotes/ImprovedBlizzardUI/blob/develop/modules/frames/player.lua#L96), but the next time you reload the UI, it will reset to their original (addon-placed) position.
This is especially an issue for me, because the default position covers roughly 1/4 of my chat frame. As a temporary solution, I've just commented out the `-- Position` blocks of the [player](https://github.com/kaytotes/ImprovedBlizzardUI/blob/develop/modules/frames/player.lua#L91-L96), [target](https://github.com/kaytotes/ImprovedBlizzardUI/blob/develop/modules/frames/target.lua#L88-L93), and [focus](https://github.com/kaytotes/ImprovedBlizzardUI/blob/develop/modules/frames/focus.lua#L83-L88) frames.

**Comment by kaytotes** [comment]
Feel free to do as above states.
