### ISSUE TITLE
Curse treats addon as classic only

### ISSUE THREAD

**Issue by astorath** [kaytotes/ImprovedBlizzardUI#164]
Curse client does not list this addon in retail WoW version: 

![image](https://user-images.githubusercontent.com/6577390/101291392-7698df00-3819-11eb-8702-fd6cba72d78b.png)

**Comment by kaytotes** [comment]
Curse is going through a transition to Overwolf and in the process have broken many things. 

Right now I don't even have access to update the addon their at all alongside many other developers. 

It's highly likely that due to this I will not be updating on Curse for some time. 

I recommend either installing via WoWInterface or an installer like WoWUp rather than Curse.

**Comment by kaytotes** [comment]
If you visit here https://www.curseforge.com/wow/addons/improved-blizzard-ui you can see that the project has been completely removed from my control and marked as archived by the great overwolf team without my knowledge or consent.

**Comment by kaytotes** [comment]
Closing this as unfortunately there is nothing I can do yet. 

Overwolf are saying some time before the end of the month as best guess.
