### ISSUE TITLE
TBC Party frames have disappeared as of 08/06/2021

### ISSUE THREAD

**Issue by maken30** [kaytotes/ImprovedBlizzardUI#178]
Hey mate, there was a minor update this morning and when I've logged in my party frames have disappeared. ive tried a few thing like resetting my folders etc but it doesnt work with your UI.

**Comment by maken30** [comment]
The TBC classic one

**Comment by kaytotes** [comment]
I won't be able to take a look at this until the weekend. Blame blizzard for breaking their API with "minor" patches.

**Comment by maken30** [comment]
Yeah no worries, in the meantime ive just switched the in game menu to
display raid profiles instead which works.

**Comment by kaytotes** [comment]
I don't have a reliable way to test the party frames as it requires two fully paid up WoW subscriptions / accounts. 

If possible please install these then provide me the error message.

https://www.curseforge.com/wow/addons/bugsack
https://www.curseforge.com/wow/addons/bug-grabber

**Comment by kaytotes** [comment]
@maken30 This will not be fixed. I don't know why but Blizzard have decided to port the Retail party frames back to TBC Classic with the latest build. They were heavily locked down as of Battle For Azeroth. 

What i'm most likely to do is just straight up remove this code as it _only_ works in Classic Era rather than Retail or TBC.

Sorry, i've tried to fix this in retail for years. The only solution is to create completely custom party frames which is way too much effort.

**Comment by kaytotes** [comment]
See: https://github.com/kaytotes/ImprovedBlizzardUI/issues/154

**Comment by maken30** [comment]
Yeah fair enough mate, ill keep my eye on an update, i think this UI is the best one!

**Comment by kaytotes** [comment]
Believe me this annoys me 100x more than anyone else. They did similar actions that completely broke the action bar changes I used to have. With each passing update from Blizz it becomes more and more impossible to get this UI how I personally want it.

**Comment by maken30** [comment]
Hey mate, I am curious about what addons you also use? like nameplate
addons etc?

**Comment by Jack8713** [comment]
i also have this problem .

**Comment by kaytotes** [comment]
@Jack8713 This is marked as won't fix. 

@maken30 I use nothing else except this and bigwigs

**Comment by kaytotes** [comment]
I've re-opened this as a fellow addon dev has reached out with some advice that i'm experimenting with. Don't want to forget this issue by leaving it closed.

**Comment by kaytotes** [comment]
@maken30 Are you on EU or US servers?

**Comment by maken30** [comment]
Hey mate, I was wondering if there was any way to extend improved blizzard
UI font to nameplates above the target? it looks like it still uses the
default blizzard font and I'm not sure how easy it is to change it?

**Comment by kaytotes** [comment]
I haven't touched the nameplates before because as far as I know these are a protected frame nightmare due to them being used to exploit over the years. However, due to this UI embedding LibSharedMedia and hooking up the Improved Blizzard UI font into that as far as I'm aware pretty much any of the major nameplate addons should work and (hopefully) let you pick the font so long as they are also using LibSharedMedia. This is quite common.

**Comment by kaytotes** [comment]
![image](https://user-images.githubusercontent.com/7526918/121955319-b8ba5480-cd57-11eb-8733-cbaeb2f35687.png)

Can confirm that at the very least Plater supports this.

**Comment by maken30** [comment]
Ah fair enough, yeah I've tried a few of the nameplate addons and they do
let you change font but I honestly don't like the aesthetic of most of
them, I had plater for abit.
