### ISSUE TITLE
Focus frame issues

### ISSUE THREAD

**Issue by sconzen** [kaytotes/ImprovedBlizzardUI#30]
Noticed that the focus frame has some wonky behaviour.

1. initially the focus frame floats over the chat and player frame, with improved blizzard ui styling (class colored name bar)
2. changing the focus frame to "larger" jumps the focus frame down over the chat. focus frame loses class colored name bar.
3. changing the focus frame back to the smaller frame shrinks it smaller than in step one, and still no class colored name bar. Still floating over the chat.

In all scenarios, the focus frame is not movable just like the player and target frame. Makes sense to not have them movable, since they're already in a great position, but the focus frame position should either be movable or in a better spot by default.
[
screenshots](http://imgur.com/a/WJYz7)

PS. love the ui

PPS. posted this on wowinterface 2 months ago. just thought I'd try posting it here too, just in case you're still playing.

**Comment by kaytotes** [comment]
Just responding to this now. Haven't been playing retail but resubbed today. Will be taking a look at this.

**Comment by kaytotes** [comment]
I have addressed this with 1.7.2 which is now pending on WoWInterface and Curse.

This was caused by how I was parenting the focus frame which caused it to display correctly at 2560x1440 but not any other resolutions. I've corrected this now and the "Larger Focus Frame" and "Smaller Focus Frame" now simply toggles what information is displayed on the Focus Frame rather than size or positioning.
