### ISSUE TITLE
Quest Tracker misbehaves

### ISSUE THREAD

**Issue by kiskunk** [kaytotes/ImprovedBlizzardUI#61]
I would like to use ImprovedBlizzardUI with the following addons:
-EasyFrames
-SexyMap

My problem is that the quest tracker always pops into random positions and even MoveAnything can't fix it, because it simply moves away on its own, like its anchor point gets random. Without making any changes the default position of the objective tracker is a little to the left from the center of the screen.

**Comment by kaytotes** [comment]
Both of those addons are going to cause conflicts 100%.

**Comment by sphvn** [comment]
Only way I can potentially see something like this working is if you had the ability to toggle off the minimap customisations completely, albeit this is a bit of work just to try and play with other add ons.

**Comment by kaytotes** [comment]
It would be easy enough to just add a configuration for it on the
PLAYER_ENTERING_WORLD event in minimap.lua but if I'm honest this is
something I make a relatively firm stance on. I don't implement workarounds
for conflicts in other add-ons as the original goal, and still primary
focus, of this add-on is purely because I wanted to only ever have to
install one and it is always intended as a set package.

The only exception would be if I broke something like DBM or Recount
somehow.
