### ISSUE TITLE
Disable Target of Focus

### ISSUE THREAD

**Issue by xMarok** [kaytotes/ImprovedBlizzardUI#67]
If possible, a way to disable the Focus' Target frame would be awesome.

**Comment by xMarok** [comment]
Ah okay. So changing the CVar for Target of Target does disable it, but it _also_ disables the actual Target of Target. I'm trying to just disable the Focus Frame target of target. I can "disable" it by doing `FocusFrameToT:SetScale(0.0001)` (Hide doesn't work), but I would assume there's probably a better way of doing that.

**Comment by kaytotes** [comment]
Aye there's definitely better ways of doing this but I'll have to sit down and make sure this is well tested before releasing so might take a bit longer. Believe me something as simple as hiding Blizzard stuff never ends up simple since they have a habit of recreating or moving things on the most random of events.
