### ISSUE TITLE
Quest/Item Ability being drawn under the hotbars.

### ISSUE THREAD

**Issue by Maestar** [kaytotes/ImprovedBlizzardUI#72]
The quest/item action button that shows up for some quests/fights/events is being drawn under the action bars and renders it almost entirely unclickable.

Screenshot examples: 
http://puu.sh/zUOD7/a854fd10ce.png
http://puu.sh/zUOOS/5baa387344.png

**Comment by kaytotes** [comment]
If possible could you provide me with an example quest so I can reproduce?

**Comment by Maestar** [comment]
yes! Here is the exact quest I had the issue with: 
http://www.wowhead.com/quest=11310/warning-some-assembly-required
(I'm so sorry its in a chain, if I find another one, I will supply it as well)

When the ui is disabled, I get the Special Action Button for this quest, so I suspect its tied to an issue with that.

**Comment by kaytotes** [comment]
Cheers for that. I'll quickly make a DK and get it to that quest over today and tomorrow.

**Comment by kaytotes** [comment]
Thankfully the [4th DK Quest](http://www.wowhead.com/quest=12641/death-comes-from-on-high) causes this and is easily repeatable. Turns out it's the Possession Bar. I've [fixed this now](https://github.com/kaytotes/ImprovedBlizzardUI/commit/e52ffb3d45b5982d33fd67fe9d8ee72147f473be) but am doing some more local testing before I deploy to Curse and WoWInterface.
