### ISSUE TITLE
Health Numbers (K, M, B)

### ISSUE THREAD

**Issue by xMarok** [kaytotes/ImprovedBlizzardUI#87]
I would really love to see health in millions / billions where it makes sense.

I think 3 digits for everything might be best. For example:
550 - 550
1550 - 1.55 K
15,550 - 15.5 K
155,000 - 155 K
1,550,000 - 1.55 M
15,500,000 - 15.5 M
155,000,000 - 155 M
1,550,000,000 - 1.55 B

Probably didn't need to write all that out, but you get the idea.

**Comment by sphvn** [comment]
Everything is getting severely squashed in BfA, I query how much of this will be needed.

**Comment by kaytotes** [comment]
It is not needed. Numbers on PTR are already squished.

On 26 Jun 2018 17:43, "Stephen Underwood" <notifications@github.com> wrote:

Everything is getting severely squashed in BfA, I query how much of this
will be needed.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kaytotes/ImprovedBlizzardUI/issues/87#issuecomment-400383699>,
or mute the thread

**Comment by xMarok** [comment]
Well, boss health is still in the millions. Regardless of whether or not shortening billions is needed, I don't think everything should be expressed in thousands (or there should at least be the option).

**Comment by kaytotes** [comment]
Considering how much Blizzard has changed with 8.0 I'm currently unsure either but will go digging.
