### ISSUE TITLE
/imp command dosen't work

### ISSUE THREAD

**Issue by Naturalie** [kaytotes/ImprovedBlizzardUI#93]
I'm trying to use /imp command to customize ImprovedBlizzardUI. It dosen't work tho, atleast for now.
Greets :D

**Comment by kaytotes** [comment]
I haven't been able to replicate this. Working fine for me.

**Comment by Kalinnka** [comment]
/imp is not working for me neither

**Comment by kaytotes** [comment]
Are you both using the latest build? Any other addons installed? etc

Seems to be working for me just fine.

**Comment by Kalinnka** [comment]
I try with only improved and don't work, the customize window don't open
I delete it again and reinstall. And now i got a LUa Error !

https://imgur.com/a/KfHBGrC

**Comment by kaytotes** [comment]
Try a /reload. Perhaps the config isnt setting. Unsure as I use an external library for that. I'll have to investigate.

**Comment by kaytotes** [comment]
I've just tested by deleting my SavedVariables for this addon. Definitely as I said above. Config not setting on first load. A /reload will fix.

**Comment by Kalinnka** [comment]
Look, i do everything,. In my last attempt i copy my addons to a new folder on my desktop, then i delete de interface folder, start the game to a new folder appear. copy my addons back, when i try to select Improved, this show up.

https://imgur.com/a/h37tCA6

**Comment by kaytotes** [comment]
I cant see the issue. It's clearly not enabled. The dependency it's talking about is a Blizzard addon. That is completely normal. 

The issue with your method is that you removed all your addons, then put them straight back. How was that supposed to fix something when the outcome is nothing has changed?

**Comment by Kalinnka** [comment]
I delete Improved in twitch with the option to delete every change made, and then install back. Not working.

**Comment by kaytotes** [comment]
Do the following.

Remove ALL add-ons from your interface folder.

Install JUST improved blizzard UI through twitch.

Boot the game and enable the add-on.

Log in.

If you get the framesdb error just do one /reload and it's gone forever.

If after all of the above it's still not working then I'm stumped.

**Comment by Kalinnka** [comment]
Like this?
https://imgur.com/a/wHAA3Mt

**Comment by kaytotes** [comment]
Please just drag and drop the screenshot directly into here. Imgur is a
terrible host and doesn't work correctly on mobile. Can't even read the
error.

Have you done the /reload I mentioned?

If so and it's still broken then I'm stumped and I guess you just can't use
the UI

**Comment by Kalinnka** [comment]
![imp](https://user-images.githubusercontent.com/20690203/42910808-3d94719c-8abf-11e8-9957-ab2b4feda68a.jpg)
![wowscrnshot_071818_190935](https://user-images.githubusercontent.com/20690203/42910822-4b14af58-8abf-11e8-89a3-fd457dce7b3c.jpg)

**Comment by Kalinnka** [comment]
I try to reload, nothing changes, i'll try delete WTF, Cache and Interface and look if this works

**Comment by kaytotes** [comment]
That's the config issue I've mentioned multiple times. Have you done a
/reload in game?

**Comment by kaytotes** [comment]
Remember that after you do that you WILL get the config error. Do the
/reload after that happens.

Like I said if after doing all of the above it's still not working there is
nothing I can do.

**Comment by Kalinnka** [comment]
Dude, i don't know what happen, yesterday i go raid with my guild, i use the default blizzard ui. I delete your addon, today i was updating some addons and i try install it again, for a last chance because i really love this UI. And just work... Simple like that, i do nothing different, just work...

**Comment by kaytotes** [comment]
Patch days are weird.

On 19 Jul 2018 22:55, "Kalinnka" <notifications@github.com> wrote:

Dude, i don't know what happen, yesterday i go raid with my guild, i use
the default blizzard ui. I delete your addon, today i was updating some
addons and i try install it again, for a last chance because i really love
this UI. And just work... Simple like that, i do nothing different, just
work...

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/kaytotes/ImprovedBlizzardUI/issues/93#issuecomment-406426340>,
or mute the thread
