### ISSUE TITLE
Action Bars: Can not change scale

### ISSUE THREAD

**Issue by Pnycar** [kaytotes/ImprovedBlizzardUI#95]
Having a problem with changing the scale of the action bars. Moving the slider then hitting ok does nothing. /reload also does nothing to solve the problem.

**Comment by kaytotes** [comment]
Oversight on my part. The action bars used to use custom art to replicate
the BfA action bars so I also easily scaled them.

Now the add-on basically uses most of Blizzards code for that.

I should get rid of the config option.

On 19 Jul 2018 01:36, "Pnycar" <notifications@github.com> wrote:

Having a problem with changing the scale of the action bars. Moving the
slider then hitting ok does nothing. /reload also does nothing to solve the
problem.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kaytotes/ImprovedBlizzardUI/issues/95>, or mute the
thread

**Comment by kaytotes** [comment]
Further details here #98
